<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\overwrite\EntityTypeInfo;

/**
 * Implements hook_entity_type_alter().
 *
 * Adds 'overwrite' link template 
 * @see EntityTypeInfo.php
 */
function overwrite_entity_type_alter(array &$entity_types) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityTypeInfo::class)
    ->entityTypeAlter($entity_types);
}

/**
 * Implements hook_entity_operation().
 * 
 * Adds 'Overwrite' tab
 * @see EntityTypeInfo.php
 */
function overwrite_entity_operation(EntityInterface $entity) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityTypeInfo::class)
    ->entityOperation($entity);
}

