<?php


/**
 *  implements hook_entity_load();
 */
function overwrite_activate_entity_load(array $entities, $entity_type_id) {
  $current_path = \Drupal::service('path.current')->getPath();
  foreach($entities as $entity) {
    $entity_type = $entity->getEntityType();

    if(!$entity_type->hasLinkTemplate('overwrite')) {
        continue;
    }

    //Do not apply overwrites to Entity Form
    $entity_edit_form = $entity->toUrl('edit-form');
    if($entity_edit_form && $current_path == $entity_edit_form->toString()) {
      continue;
    }

    $overwrites = \Drupal\overwrite\Controller\OverwriteController::getOverwrites($entity_type_id, $entity->id());
    if(!empty($overwrites)) {
      foreach($overwrites as $overwrite) {
        $values = $overwrite->getFieldValue();
        $fieldname = $overwrite->getRelatedFieldname();
        switch($overwrite->getMethod()) {
          case 'replace':
            $entity->{$fieldname}->setValue($values->getValue());
            break;
          case 'append':
            foreach($values as $value) {
              $entity->{$fieldname}->appendItem($value->getValue());
            }
            break;
          case 'prepend':
            $field_values = $entity->{$fieldname}->getValue();
            $entity->{$fieldname}->setValue(array_merge($values->getValue(), $field_values));
            break;
        }
      }
    }
  }
}

